### ISSUE TITLE
Faucetの情報を載せてほしいです。(ただしmainnetは無いので「無い」と記載してほしいです)

### ISSUE THREAD

**Issue by yas-oasys** [oasysgames/oasys-docs#62]
Faucetの情報を載せる(Mainnet, Testnet, Sandverse)←Validator建てるときに聞かれるので今後増えそうに思います
→Mainnnetは公式のものがないので、無いという記載がいいと思います。

https://discord.com/channels/892295154025783346/1036448707605975101/1115808569217011784

**Comment by tak1827** [comment]
こちらに整理されています。
https://docs.oasys.games/docs/staking/rpc-endpoint/1-1-rpc-endpoint
